name: Python CI

on: [push] # Run this workflow every time you push to any branch

jobs:
  build:
    runs-on: ubuntu-latest # Use a standard Linux machine

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4 # A pre-built action to get your code

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests with pytest
      run: pytest
